# Generated by Django 4.1.7 on 2023-04-20 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BHSLFX', '0002_alter_accounts_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
