# Generated by Django 4.1.7 on 2023-04-20 18:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BHSLFX', '0005_alter_accounts_owner_delete_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='UserAccount',
        ),
    ]
